#!/bin/bash
echo "Starting Installer"

$(ls -al /dev/disk/by-partuuid | awk '{ print "export " $11 "=" $9}' | sed 's/..\/..\///g' | sed -e '1,3d')

ROOT=/dev/disk/by-partuuid/$vda3


POOLS=( $(zpool list | awk '{ print $1 }' | sed -e '1d') )


if [ "${#POOLS[@]}" -eq "0" ]; then

zpool create -f -o ashift=12           \
             -O acltype=posixacl       \
             -O relatime=on            \
             -O xattr=sa               \
             -O dnodesize=legacy       \
             -O normalization=formD    \
             -O mountpoint=none        \
             -O canmount=off           \
             -O devices=off            \
             -O compression=lz4        \
             -R /mnt                   \
             rpool $ROOT

echo "rpool created!"

fi


zfs create -o canmount=off -o mountpoint=none rpool/data
zfs create -o canmount=off -o mountpoint=none rpool/ROOT


zfs create -o canmount=noauto -o mountpoint=/ rpool/ROOT/default
zfs mount rpool/ROOT/default

zfs create -o mountpoint=/home rpool/data/home
zfs create -o mountpoint=/root rpool/data/home/root
chmod 700 /mnt/root

zfs create -o mountpoint=/var -o canmount=off     rpool/var
zfs create                                        rpool/var/log

zfs create -o mountpoint=/var/lib -o canmount=off rpool/var/lib
zfs create                                        rpool/var/lib/libvirt
zfs create -o com.archlinux.zsys:auto-snapshot=false  rpool/var/lib/docker
zfs create -o com.archlinux.zsys:auto-snapshot=false  rpool/var/lib/nfs

zfs create -o com.archlinux.zsys:auto-snapshot=false  rpool/tmp

zpool export rpool
zpool import -d /dev/disk/by-partuuid -R /mnt rpool -N
zpool set bootfs=rpool/ROOT/default rpool
zfs mount -a

pacstrap /mnt base linux linux-firmware base-devel


#cp /etc/zfs/zpool.cache /mnt/etc/zfs/zpool.cache
#zpool set cachefile=/etc/zfs/zpool.cache rpool
