#!/bin/bash
echo "Starting Arch ZFS Installer!"

DISK=/dev/vda

wipefs -af $DISK
sgdisk --zap-all $DISK

sgdisk -a1 -n1:24K:+1000K -t1:EF02 $DISK
sgdisk     -n2:1M:+512M   -t2:EF00 $DISK
sgdisk     -n3:0:+1G      -t3:8200 $DISK
sgdisk     -n4:0:0        -t4:BF00 $DISK

sleep 5

mkfs.vfat ${DISK}2
mkswap ${DISK}3
swapon ${DISK}3

sleep 2

# Check zfs module loaded or not.
test -n "$(grep -e "^zfs " /proc/modules)" && echo "zfs Loaded" || (echo "zfs Not loaded" && exit)

zpool create -f -o ashift=12 \
  -O acltype=posixacl \
  -O relatime=on \
  -O xattr=sa \
  -O dnodesize=legacy \
  -O normalization=formD \
  -O mountpoint=none \
  -O canmount=off \
  -O devices=off \
  -R /mnt \
  zroot ${DISK}4

sleep 2
  
zfs create -o mountpoint=none zroot/data
zfs create -o mountpoint=none zroot/ROOT
zfs create -o mountpoint=/ -o canmount=noauto zroot/ROOT/default
zfs create -o mountpoint=/home zroot/data/home

zfs create -o mountpoint=/var -o canmount=off zroot/var
zfs create zroot/var/log

zfs create -o mountpoint=/var/lib -o canmount=off zroot/var/lib
zfs create zroot/var/lib/libvirt
zfs create zroot/var/lib/docker

zpool export zroot
zpool import -d ${DISK}4 -R /mnt zroot -N

zfs mount zroot/ROOT/default
zfs mount -a

zpool set bootfs=zroot/ROOT/default zroot
zpool set cachefile=/etc/zfs/zpool.cache zroot
mkdir -p /mnt/{etc/zfs,boot/efi}
cp /etc/zfs/zpool.cache /mnt/etc/zfs/zpool.cache

mount ${DISK}2 /mnt/boot/efi

pacman -Syy
pacstrap /mnt base base-devel linux linux-firmware linux-headers grub efibootmgr \
  gnome-shell gnome-initial-setup totem gnome-backgrounds nautilus gnome-terminal gedit eog evince gnome-system-monitor \
  gnome-disk-utility gnome-screenshot gnome-logs gnome-font-viewer yelp gnome-photos \
  file-roller epiphany gnome-calculator gnome-calendar gnome-characters gnome-keyring \
  gnome-software gnome-user-share gvfs gnome-shell-extensions gnome-maps gnome-contacts \
  gnome-color-manager sushi cheese gnome-remote-desktop gnome-control-center \
  xdg-user-dirs xdg-user-dirs-gtk xdg-desktop-portal-gnome gdm zsh grml-zsh-config networkmanager \
  gst-plugins-base gst-plugins-good gst-plugins-ugly gst-plugins-bad gst-libav noto-fonts

genfstab -U -p /mnt | sed -e '/^zroot/d;/^#\ zroot/d' > /mnt/etc/fstab

curl -L https://git.io/Jsfw2 > /mnt/etc/pacman.d/mirrorlist-archzfs
tee -a /mnt/etc/pacman.conf <<- 'EOF'

[archzfs-testing]
Include = /etc/pacman.d/mirrorlist-archzfs

[archzfs]
Include = /etc/pacman.d/mirrorlist-archzfs
EOF


echo '[daemon]' > /etc/gdm/custom.conf
echo 'InitialSetupEnable=True' >> /etc/gdm/custom.conf

cat << EOF | arch-chroot /mnt /bin/sh
timedatectl set-timezone Europe/Paris
sed -i '/en_US.UTF-8/s/^#//g' /etc/locale.gen
locale-gen
echo LANG=en_US.UTF-8 > /etc/locale.conf
echo workstation > /etc/hostname
echo '127.0.0.1	localhost' > /etc/hosts
echo '::1		localhost' >> /etc/hosts
echo '127.0.1.1	workstation' >> /etc/hosts

pacman -Syu

sed -i'' 's/filesystems\ keyboard\ fsck/keyboard\ zfs\ filesystems/g' /etc/mkinitcpio.conf
pacman -Sy --needed --noconfirm zfs-dkms glibc
# mkinitcpio -p linux

sed -i'' 's/GRUB_CMDLINE_LINUX=""/GRUB_CMDLINE_LINUX="root=ZFS=zroot\/ROOT\/default"/g' /etc/default/grub

curl -L https://archzfs.com/archzfs.gpg |  pacman-key -a -
pacman-key --lsign-key $(curl -L https://git.io/JsfVS)


grub-install --target=x86_64-efi --bootloader-id=ARCHLINUX --efi-directory=/boot/efi
grub-mkconfig -o /boot/grub/grub.cfg

systemctl enable zfs-import-cache
systemctl enable zfs-import-scan
systemctl enable zfs-mount
systemctl enable zfs-share
systemctl enable zfs-zed
systemctl enable zfs.target

systemctl enable gdm
systemctl enable NetworkManager


echo "root:root" | chpasswd
chsh -s /bin/zsh
EOF

umount /mnt/boot/efi
zfs umount -a
zpool export zroot
