on: [push, pull_request]

jobs:
  armv7_job:
    # The host should always be Linux
    runs-on: ubuntu-latest
    name: Build on ubuntu-latest aarch64


    steps:
      - uses: actions/upload-artifact@v3
        with:
          path: $HOME/artifacts
      - name: Install the toolchain
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
          sudo apt-get install gcc-aarch64-linux-gnu --assume-yes

      - name: Fetch Upstream
        run: |
          git clone --quiet --depth=1 https://github.com/torvalds/linux && cd linux
          # curl -L https://raw.githubusercontent.com/raspberrypi/linux/rpi-5.15.y/arch/arm/configs/bcm2711_defconfig --output ./arch/arm64/configs/bcm2711_defconfig
          # curl -L https://raw.githubusercontent.com/raspberrypi/linux/rpi-5.15.y/arch/arm/boot/dts/Makefile --output /tmp/Makefile
          # tail -n 10 /tmp/Makefile >> ./arch/arm/boot/dts/Makefile
          # mkdir /tmp/linux && git clone --depth=1 https://github.com/raspberrypi/linux /tmp/linux
          # cp -r /tmp/linux/arch/arm/boot/dts/overlays ./arch/arm/boot/dts
          # ln -s ../../../arm/boot/dts/overlays arch/arm64/boot/dts/overlays
      
          cp arch/arm/configs/bcm2835_defconfig arch/arm64/configs/bcm2835_defconfig
          echo 'CONFIG_ARM_LPAE=y' >> arch/arm64/configs/bcm2835_defconfig
          echo 'CONFIG_DRM_VC4=y' >> arch/arm64/configs/bcm2835_defconfig
          echo 'CONFIG_DRM_V3D=y' >> arch/arm64/configs/bcm2835_defconfig
          echo 'CONFIG_USB_DWC3=y' >> arch/arm64/configs/bcm2835_defconfig
          echo 'CONFIG_USB_DWC2=y' >> arch/arm64/configs/bcm2835_defconfig
          echo 'CONFIG_EXFAT_FS=y' >> arch/arm64/configs/bcm2835_defconfig
          echo 'CONFIG_FAT_FS=y' >> arch/arm64/configs/bcm2835_defconfig
          echo 'CONFIG_NFSD=y' >> arch/arm64/configs/bcm2835_defconfig
          echo 'CONFIG_NFS_FS=y' >> arch/arm64/configs/bcm2835_defconfig
          
          make ARCH=arm64 bcm2835_defconfig
          echo $(make kernelversion)

          make -j24 ARCH=arm64 \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CXXFLAGS="-march=armv8-a+crc -mtune=cortex-a72" \
            CFLAGS="-march=armv8-a+crc -mtune=cortex-a72" \
            Image.gz modules dtbs

          mkdir -p $HOME/artifacts/boot/overlays
          make INSTALL_MOD_PATH=$HOME/artifacts modules_install
          cp arch/arm64/boot/Image.gz $HOME/artifacts/boot/kernel8.img
          # cp arch/arm64/boot/dts/overlays/*.dtbo $HOME/artifacts/boot/overlays/
          # cp arch/arm64/boot/dts/broadcom/*.dtb $HOME/artifacts/boot/
